config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	root "posts#index"
	resources :tags, only: [:show]
	resources :categories, only: [:show]
	resources :posts do
		member do
			delete :removeImage
		end
		resources :comments
	end

	get 'search', to: "posts#search"

	namespace :admin do
		resources :categories, except: [:show]
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
	validates :name, presence: true
	has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :category
	has_many :comments, dependent: :destroy
	has_one_attached :image
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings, dependent: :destroy
	has_rich_text :content

	validates :title, presence: true
	validates :body, presence: true, length: {minimum: 10, maximum: 300}
	validates :content, presence: true, length: {minimum: 100}

	def all_tags
		self.tags.map(&:name).join(', ')
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name.strip).first_or_create!
		end
	end
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :taggings
	has_many :posts, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :post
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :set_category, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: :show

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
		@categories = Category.all.order(:name)
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to admin_categories_path
		else
			render :new
		end 
	end

	def edit
		@categories = Category.where("id != #{@category.id}").order(:name)
	end

	def update
		if @category.update(category_params)
			redirect_to admin_categories_path
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to admin_categories_path
	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :parent_id)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]

	def show
		@posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
	end

	private

		def set_category
			@category = Category.find(params[:id])
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private
		def comment_params
			params.require(:comment).permit(:author, :body)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.paginate(page: params[:page], per_page: 5)
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	def removeImage
		@post = Post.find(params[:id])

		if @post.image.attached?
			@post.image.purge_later
		end

		redirect_to edit_post_path
	end

	def search
		@posts = Post.where("title LIKE ?", "%" + params[:q] + "%")
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :image, :all_tags, :category_id, :content)
		end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find_by(name: params[:id])
		@posts = @tag.posts.paginate(:page => params[:page], :per_page => 5)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def build_breadcrumbs(category)
		result = []
		category.ancestors.each do |ancestor|
			result << content_tag(:li, class: "breadcrumb-item") do
				link_to(ancestor.name, ancestor)
			end
		end
		result << content_tag(:li, category.name, class: "breadcrumb-item active")
		result.join('').html_safe
	end

	def is_user_admin?
		if current_user.admin
			return true
		else
			return false
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def tags_navigation(tags, css)
		tags.each do |tag|
			yield(tag, css)
		end
	end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
	<% if blob.representable? %>
		<%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 600, 400]) %>
	<% end %>

	<figcaption class="attachment__caption">
		<% if caption = blob.try(:caption) %>
			<%= caption %>
		<% else %>
			<span class="attachment__name"><%= blob.filename %></span>
			<span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
		<% end %>
	</figcaption>
</figure>

app/views/admin/categories/_form.html.erb
<%= form_with model: [:admin, category] do |form| %>
	<div class="form-group">
		<%= form.label :name %><br>
		<%= form.text_field :name, {:class => 'form-control'}%>
		<%= render "shared/errors", {resource: category, field: :name} %>
	</div>

	<div class="form-group">
		<div class="form-group">
			<%= form.label :parent_id %>
			<% if category.id.present? %>
				<%= form.collection_select :parent_id, Category.where("id != #{category.id}").order(:name), 
					:id, :name, {include_blank:true}, class: 'form-control'%>
			<% else %>
				<%= form.collection_select :parent_id, Category.order(:name), :id, :name, 
					{include_blank:true}, class: 'form-control'%>
			<% end %>
		</div>
	</div>

	<div class="form-group">
		<%= form.submit :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit category</h1>

<%= render "form", category: @category %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>

<div>
	<%= link_to 'New category', new_admin_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<br>
<section id="categories">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Parent</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each_with_index do |category, n| %>
				<tr>
					<td><%= n + 1  %></td>
					<td><%= category.name %></td>
					<td><%= category.parent.name if category.parent.present? %></td>
					<td>
						<%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
						<%= link_to 'Delete', admin_category_path(category), method: :delete, 
							data: {confirm: 'Are you sure?'},class: 'btn btn-outline-danger btn-sm' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</section>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

app/views/categories/_show_name.html.erb
<% if post.category.present? %>
	<span>Category:</span>
	<%= link_to post.category.name, post.category %>
<% end %>

app/views/categories/show.html.erb
<%= render 'posts/search_field'%>
<%= render 'shared/breadcrumb', category:@category %>
<%= render 'shared/filtering_posts' %>
<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'  %>

app/views/comments/_comment.html.erb
<p>
	<strong>Author: </strong>
	<%= comment.author %>
</p>
<p>
	<strong>Comment: </strong>
	<%= comment.body %>
</p>

<% if user_signed_in? && is_user_admin? %>
	<p>
		<%= link_to 'Delete comment', [comment.post, comment], method: :delete, data: {confirm: "Are you sure?"} %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
	<p>
		<%= form.label :author %><br>
		<%= form.text_field :author, :class => 'form-control' %>
	</p>

	<p>
		<%= form.label :body %><br>
		<%= form.text_area :body, :class => 'form-control' %><br>
	</p>

	<p>
		<%= form.submit :class => 'btn btn-primary' %>
	</p>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
	<%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>RailsPvi</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css', 
			media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<header class="p-3 bg-dark text-white">
			<div class="container">
				<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
					<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
						<li><a href="<%= posts_path %>" class="nav-link px-2 text-secondary">Main page</a></li>
						<% if user_signed_in? && is_user_admin? %>
							<li><a href="<%= new_post_path %>" class="nav-link px-2 text-white">Create new post</a></li>
							<li><a href="<%= admin_categories_path %>" class="nav-link px-2 text-white">Edit categories</a></li>
						<% end %>
					</ul>
					<div class="text-end ">
						<% if user_signed_in? %>
							<%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-outline-light me-2"%>
							<%= link_to "Edit profile", edit_user_registration_path, class:"btn btn-outline-light me-2"%>				
						<% else %>
							<%= link_to "Log in", new_user_session_path, class:"btn btn-outline-light me-2" %>
							<%= link_to "Sign up", new_user_registration_path, class:"btn btn-warning" %>
						<% end %>
					</div>
				</div>
			</div>
		</header>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

	var disqus_config = function () {
	this.page.url = 'http://localhost.com<%= request.original_fullpath %>';
	this.page.identifier = '<%= @post.id %>';
	};

	(function() {
	var d = document, s = d.createElement('script');
	s.src = 'https://rails-blog-5.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
	<div class="form-group">
		<%= form.label :title %><br>
		<%= form.text_field :title, {:class => 'form-control'}%>
		<%= render "shared/errors", {resource: @post, field: :title}%>
	</div>

	<div class="form-group">
		<%= form.label :Summary %><br>
		<%= form.text_area :body, {:class => 'form-control'} %>
		<%= render "shared/errors", {resource: @post, field: :body} %>
	</div>

  	<div class="field">
    	<%= form.label :content %>
    	<%= form.rich_text_area :content %>
		<%= render "shared/errors", {resource: @post, field: :content} %>
  	</div>

	<%# Categories field %>
	<div class="form-group">
		<%= form.label :category_id %>
		<%= form.collection_select :category_id, Category.order(:name), :id, :name, {required: true}, class:'form-control' %>
		<%= render "shared/errors", {resource: @post, field: :category_id} %>
	</div>

	<%# Tags field %>
	<div class="form-group">
		<%= form.label :all_tags %>
		<%= form.text_field :all_tags, class:'form-control', placeholder: 'tag1, tag2, tag3' %>
	</div>

	<%# Image handler %>
	<div class="form-group">
		<%= render "posts/image", {post: post, myclass: 'show-image-container', width: 800, height: 600} %>

		<%# Delete image %>
		<% if post.image.attached? %>
			<%= link_to "Remove image", removeImage_post_path(@post), method: :delete %>
		<% end %>

		<%# Upload image %>
		<% if !post.image.attached? %>
			<%= form.label :Avatar %><br>
			<%= form.file_field :image, {:class => 'form-control'} %>
		<% end %>
	</div>

	<div class="form-group">
		<%= form.submit :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/posts/_image.html.erb
<% if post.image.attached? %>
	<div class="<%= myclass %>">
		<%= image_tag post.image.representation(resize_to_limit: [width, height]), class: "img-thumbnail" %>
	</div>
<% end %>

app/views/posts/_post.html.erb
<article class="mb-2">
	<section id="post-head">
		<small>
			<%= render 'posts/post_head', post: post%>
		</small>
		<h2><%= link_to post.title, post %></h2>
	</section>
	<section class="row" id="post-body">
		<%= render "posts/image", {post: post, myclass: 'ml-3 col-md-2 pr-0 pl-0', width: 200, height: 100} %>
		<div class="col-md-9 col">
			<%= post.body %>
			<small><%= render 'tags/tag', post: post %></small>
		</div>
	</section>
	<hr>
</article>

app/views/posts/_post_head.html.erb
<span class="">Created at: <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time></span>
<span class="col-md-4"><%= render 'categories/show_name', post: post%></span>

app/views/posts/_search_field.html.erb
<div class="p-3 bg-light d-flex justify-content-center mb-2">
	<form class="form-inline flex-wrap d-flex justify-content-center mt-2 mt-md-0" action="/search">
		<input class="form-control mr-sm-2 mt-2 mb-2" name="q" type="text" placeholder="Search" aria-label="Search">
		<button class="btn btn-outline-dark me-2 mt-2 mb-2" type="submit">Search</button>
	</form>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= render 'posts/search_field'%>
<div class="row">
	<div class="col-md-9">
		<h2>Posts</h2>
		<%= render @posts %>
		<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'  %>
	</div>
	<div class="col-md-3">
		<%= render 'shared/submenu' %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

app/views/posts/search.html.erb
<%= render 'posts/search_field' %>
<%= render 'shared/filtering_posts' %>

app/views/posts/show.html.erb
<% if user_signed_in?  %>
	<%= render 'posts/search_field'%>
	<div class="mb-3 mt-3 row">
		<div class="col-md-9">
			<article>
					<% if is_user_admin? %>
						<div class="form-group">
							<%= link_to "Edit", edit_post_path(@post), class: 'btn btn-outline-primary' %>
							<%= link_to "Destroy", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, 
								class: 'btn btn-outline-primary' %>
						</div>
					<% end %>
					<section id="post-head">
						<h2><%= @post.title %></h2>
						<%= render 'posts/post_head', post:@post %>
						<%= render 'tags/tag', post: @post %>
					</section>
					<section id="post-body" class="mt-4">
						<%= @post.content %>
					</section>
			</article>
			<hr>
			<section id="post-comments">
				<%= render 'posts/disqus'%>
			</section>
		</div>
		<div class="col-md-3">
			<%= render 'shared/submenu' %>
		</div>
	</div>
<% else %>
	<div class="alert alert-danger mt-4">You don't have access to this page. Log in first </div>
<% end %>

app/views/shared/_breadcrumb.html.erb
<% if category.present? %>
	<ol class="breadcrumb mb-3 mt-3">
		<%= build_breadcrumbs(category)%>
	</ol>
<% end %>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %><br>
	<% resource.errors.full_messages_for(field).each do |message| %>
		<% if resource.errors.full_messages_for(field).first == message %>
			<div class="alert alert-danger">
				<%= message  %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/shared/_filtering_posts.html.erb
<section id="posts">
	<div class="row">
		<div class="col-md-9">
			<%= render @posts %>
		</div>
		<div class="col-md-3">
			<%= render 'shared/submenu' %>
		</div>
	</div>
</section>

app/views/shared/_submenu.html.erb
<div class="text-end submenu">
	<h2>Categories</h2>
	<ul class="nav nav-pills nav-stacked">
		<% Category.roots.each do |category| %>
			<li>
				<%= link_to category.name, category, class: "list-group-item list-group-item-secondary #{'active' if current_page? (category_path(category))}" %>
				<%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
			</li>
		<% end %>
	</ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked ml-3">
	<% categories.each do |category, children| %>
		<li>
			<%= link_to category.name, category, class: "list-group-item #{'active' if current_page? (category_path(category))}" %>
			<%= render 'shared/submenu_categories', categories: children if children.present? %>
		</li>
	<% end %>
</ul>

app/views/tags/_tag.html.erb
<div class="tags-container">
    <% post.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag.name), class: "blog-tag" %>
    <% end %>
</div>

app/views/tags/show.html.erb
<%= render 'posts/search_field'%>
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
	<h2>There are no posts with such tag</h2>
<% else %>
	<%= render @posts %>
	<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'  %>
<% end %>